POPULATION_SIZE: 500 
MAX_GENERATIONS: 100  # 50, 100
VERBOSE: True
MAX_TREE_SIZE: 64     # 16, 64
MUTATION_RATE: 0.2 
OP_MUTATION_RATE: 0.2
MIN_DEPTH: 2 
INITIALIZATION_MAX_TREE_DEPTH: 16   # 6, 16
TOURNAMENT_SIZE: 3
REPODUCTION_SIZE: 300
FUNCTIONS: ['add', 'sub', 'mul', 'div', 'pow', 'sin', 'cos', 'log']
FITNESS_TYPE: 'adjusted'    # mse, rmse, nrmse, raw, adjusted, normalizedAdjusted
ERROR_EPSILON: 0.00001
ERROR_TYPE: 'r2_score'   # mse, rmse, nrmse, r2_score
MAX_EVALUATIONS: -1
MAX_HOURS: 5
NUM_RUNS: 30
SSC: 
  USE_SSC: True
  LBSS: 0.0001
  UBSS: 0.9
  MAX_TRIALS: 20