POPULATION_SIZE: 500  #1000
MAX_GENERATIONS: 50  # 50, 100
VERBOSE: True
MAX_TREE_SIZE: 8     # 16, 64
MUTATION_RATE: 0.2 
OP_MUTATION_RATE: 0.2
MIN_DEPTH: 2 
INITIALIZATION_MAX_TREE_DEPTH: 3   # 6, 16, 12
TOURNAMENT_SIZE: 3
REPODUCTION_SIZE: 300  # 700
FUNCTIONS: ['add', 'sub', 'mul', 'div', 'pow', 'sin', 'cos', 'log']
FITNESS_TYPE: 'adjusted'    # mse, rmse, nrmse, raw, adjusted, normalizedAdjusted
ERROR_EPSILON: 0.00001
ERROR_TYPE: 'r2_score'   # mse, rmse, nrmse, r2_score
MAX_EVALUATIONS: -1
MAX_HOURS: 5
NUM_RUNS: 30
SSC: 
  USE_SSC: False
  LBSS: 0.0001
  UBSS: 2.0
  MAX_TRIALS: 10