POPULATION_SIZE: 25 
MAX_GENERATIONS: 20
VERBOSE: True
MAX_TREE_SIZE: 10 
MUTATION_RATE: 0.3 
OP_MUTATION_RATE: 0.3
MIN_HEIGHT: 2 
INITIALIZATION_MAX_TREE_HEIGHT: 4 
TOURNAMENT_SIZE: 4
FUNCTIONS: ['add', 'sub', 'mul', 'div']