K_MAX: 4  #4, 6 (for yacht)
MIN_INIT_TREE_DEPTH: 2
MAX_INIT_TREE_DEPTH: 4
MAX_TREE_DEPTH: 6
MAX_ITERATIONS: 1000  # 1000; 2000 for yacht
MAX_HOURS: 3
NUM_RUNS: 30
FUNCTIONS: ['add', 'sub', 'mul', 'div', 'pow', 'sin', 'cos', 'log']